export const ROLES = {
  ADMIN: 'ADMIN',
  BUSINESS: 'BUSINESS',
  CUSTOMER: 'CUSTOMER',
}

export const BUSINESS_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  BLOCKED: 'BLOCKED',
}

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
}

export const INVOICE_STATUS = {
  GENERATED: 'GENERATED',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
}

export const BILLING_CYCLE = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
}
